name: Daily Commit Workflow

on:
  schedule:
    - cron: '5 6 * * *'  # Runs daily at 06:05 UTC
  workflow_dispatch:      # Optional: allows manual trigger from Actions tab

jobs:
  commit:
    name: Daily Commit Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Daily Commit by 23f1000504@ds.study.iitm.ac.in
        run: |
          echo "Automated daily update: $(date -u)" >> daily-log.txt
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add daily-log.txt
          git commit -m "Automated daily update: $(date -u)"
          git push
